version: '3.3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginxb
    ports:
      - 443:443
    container_name: nginxc
    env_file:
      - .env
    networks:
      - dnet
    depends_on:
      - wordpress
    volumes:
      - /home/abrun/data/wordpress:/home/srcs/wp-data
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    image: wordpressb
    container_name: wordpressc
    env_file:
      - .env
    networks:
      - dnet
    depends_on:
      - mariadb
    volumes:
      - /home/abrun/data/wordpress:/home/srcs/wp-data
    restart: on-failure
  mariadb:
    build: ./requirements/mariadb
    image: mariadbb
    container_name: mariadbc
    env_file:
      - .env
    networks:
      - dnet
    volumes:
      - /home/abrun/data/mariadb:/home/srcs/db-data
    restart: on-failure

networks:
  dnet: {}
