version: "3.5"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - dbData:/var/lib/mysql
    networks:
      - dnet
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wpData:/var/www/site
    networks:
      - dnet
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wpData:/var/www/site
    networks:
      - dnet
    restart: always

networks:
  dnet:
    name: dnet
    driver: bridge

volumes:
  wpData:
    driver: local
    name: wpData
    driver_opts:
      type: none
      o: bind
      device: /home/abrun/data/wordpress
  dbData:
    driver: local
    name: dbData
    driver_opts:
      type: none
      o: bind
      device: /home/abrun/data/mariadb
