version: '3.3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    container_name: nginx
    env_file:
      - .env
    networks:
      - dnet
    depends_on:
      - wordpress
    volumes:
      - /home/abrun/data/wordpress:/var/www/html
    restart: on-failure
    links:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - dnet
    depends_on:
      - mariadb
    volumes:
      - /home/abrun/data/wordpress:/var/www/html
    restart: on-failure
    links:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - dnet
    volumes:
      - /home/abrun/data/mariadb:/var/lib/mysql
    restart: on-failure

networks:
  dnet:
    name: dnet
