ALTER USER 'root'@'localhost' IDENTIFIED BY 'rtpass';
CREATE DATABASE IF NOT EXISTS wpData;
CREATE USER IF NOT EXISTS 'abrun'@'%' IDENTIFIED BY 'abpass';
CREATE USER IF NOT EXISTS 'chuck'@'%' IDENTIFIED BY 'chpass';
GRANT ALL PRIVILEGES ON wpData.* TO 'chuck'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'chuck'@'%';
FLUSH PRIVILEGES;
